### ISSUE TITLE
Grok parser custom field name concurrency issues.

### ISSUE THREAD

**Issue by nityanandagohain** [SigNoz/signoz-otel-collector#66]
If we use something like `%{COMMONLOG}` to parse a log line, the benchmarks run well and there is no concurrency issue.

but whenever we add our own variables like `%{DATA:podname}_%{DATA:namespace}_%{GREEDYDATA:container_name}-%{WORD:container_id}.log`, there is concurrency issue.

```
fatal error: concurrent map writes

goroutine 98 [running]:
runtime.throw({0x1027c9330?, 0x0?})
	/usr/local/go/src/runtime/panic.go:992 +0x50 fp=0x14000455b70 sp=0x14000455b40 pc=0x1021dc850
runtime.mapassign_faststr(0x14000119720?, 0x1027e9662?, {0x14000468018, 0x7})
	/usr/local/go/src/runtime/map_faststr.go:212 +0x3bc fp=0x14000455be0 sp=0x14000455b70 pc=0x1021ba72c
github.com/vjeantet/grok.(*Grok).aliasizePatternName(...)
	/Users/nityanandagohain/go/pkg/mod/github.com/vjeantet/grok@v1.0.1/grok.go:390
github.com/vjeantet/grok.(*Grok).denormalizePattern(0x14000048280, {0x1027e965b, 0x57}, 0x57?)
	/Users/nityanandagohain/go/pkg/mod/github.com/vjeantet/grok@v1.0.1/grok.go:345 +0x1ec fp=0x14000455dd0 sp=0x14000455be0 pc=0x1024c32ec
github.com/vjeantet/grok.(*Grok).compile(0x14000048280, {0x1027e965b, 0x57})
	/Users/nityanandagohain/go/pkg/mod/github.com/vjeantet/grok@v1.0.1/grok.go:315 +0x194 fp=0x14000455e40 sp=0x14000455dd0 pc=0x1024c2f34
github.com/vjeantet/grok.(*Grok).Parse(0x0?, {0x1027e965b?, 0x0?}, {0x140002d0400, 0x79})
	/Users/nityanandagohain/go/pkg/mod/github.com/vjeantet/grok@v1.0.1/grok.go:232 +0x30 fp=0x14000455e80 sp=0x14000455e40 pc=0x1024c2620
github.com/SigNoz/signoz-otel-collector/pkg/parser/grok.(*Parser).match(0x14000398900, {0x140002d0400, 0x79})
	/Users/nityanandagohain/projects/signoz-otel-collector/signoz-otel-collector/pkg/parser/grok/grok.go:138 +0xa4 fp=0x14000455f60 sp=0x14000455e80 pc=0x1027ae0e4
```

someone reported this issue but closed it https://github.com/vjeantet/grok/issues/33

**Comment by nityanandagohain** [comment]
Created a fork for fixing the issue https://github.com/SigNoz/grok


created a PR for upstream as well https://github.com/vjeantet/grok/pull/37
